import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#f6f7f2',
  },
  shell: {
    flex: 1,
    flexDirection: 'row',
  },
  main: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
  },
  homeHeader: {
    flexShrink: 0,
    backgroundColor: '#fbfcf8',
    borderBottomWidth: 1,
    borderColor: '#e2e7dd',
  },
  homeHeaderContent: {
    width: '100%',
    maxWidth: 1350,
    alignSelf: 'center',
    paddingHorizontal: 40,
    paddingVertical: 12,
  },
  loading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 15,
  },
  sidebar: {
    width: 220,
    padding: 28,
    paddingTop: 45,
    borderRightWidth: 1,
    borderColor: '#e2e7dd',
    backgroundColor: '#fbfcf8',
  },
  sidebarQuote: {
    fontSize: 19,
    lineHeight: 32,
    color: '#627356',
    marginTop: 15,
    marginBottom: 40,
  },
  content: {
    padding: 40,
    width: '100%',
    maxWidth: 1350,
    alignSelf: 'center',
    paddingBottom: 45,
  },
  hidden: {
    display: 'none',
  },
  editorScreen: {
    flex: 1,
  },
  editorHeader: {
    backgroundColor: '#fbfcf8',
    borderBottomWidth: 1,
    borderColor: '#e2e7dd',
  },
  editorHeaderContent: {
    width: '100%',
    maxWidth: 780,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  editorContent: {
    width: '100%',
    maxWidth: 780,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 40,
  },
  foodSelectionQuery: {
    paddingTop: 0,
    paddingBottom: 16,
    gap: 8,
  },
  foodSelectionSections: {
    paddingTop: 16,
    gap: 16,
  },
  selectedFoods: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    padding: 12,
  },
  mealFoodEditor: {
    marginVertical: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#dce3d5',
    borderRadius: 8,
  },
  eyebrow: {
    fontSize: 10,
    letterSpacing: 2.5,
    color: '#788c69',
    fontWeight: '600',
  },
  subtitle: {
    fontSize: 13,
    lineHeight: 23,
    color: '#7c8b72',
    marginTop: 6,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  between: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  recordDateTitle: {
    fontSize: 12,
  },
  datebar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  button: {
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 8,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    fontSize: 12,
    color: '#42633b',
    fontWeight: '500',
  },
  dangerText: {
    color: '#a14332',
  },
  dangerButton: {
    backgroundColor: '#fbece8',
  },
  secondaryButton: {
    backgroundColor: '#EAEDF1',
  },
  secondaryText: {
    color: '#526174',
  },
  primary: {
    backgroundColor: '#245d48',
    paddingHorizontal: 22,
  },
  selected: { backgroundColor: '#e7eedc' },
  notice: {
    padding: 12,
    backgroundColor: '#eaf0df',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  body: {
    fontSize: 13,
    lineHeight: 22,
    color: '#52654b',
  },
  caption: {
    fontSize: 11,
    lineHeight: 19,
    color: '#849078',
  },
  columns: { gap: 22 },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2f4536',
  },
  card: {
    padding: 18,
    borderWidth: 1,
    borderColor: '#e2e7dd',
    borderRadius: 15,
    backgroundColor: '#fff',
  },
  nutritionSummary: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderColor: '#eef0e9',
  },
  nutritionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 16,
  },
  nutritionMetric: {
    flexGrow: 1,
    flexBasis: 140,
    minWidth: 0,
    padding: 12,
    borderRadius: 10,
    backgroundColor: '#f6f8f2',
    gap: 4,
  },
  nutritionAmount: {
    fontSize: 24,
    fontWeight: '600',
    color: '#245d48',
  },
  nutritionProgressTrack: {
    height: 5,
    borderRadius: 3,
    backgroundColor: '#e2e8da',
    overflow: 'hidden',
    marginVertical: 4,
  },
  nutritionProgressFill: {
    height: '100%',
    backgroundColor: '#245d48',
    borderRadius: 3,
  },
  nutritionProgressOver: {
    backgroundColor: '#a87731',
  },
  nutritionOverText: {
    color: '#936825',
  },
  nutritionGoalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 24,
  },
  portionUnits: {
    marginTop: 20,
    gap: 8,
  },
  portionNutritionSummary: {
    marginTop: 16,
    padding: 14,
    borderRadius: 12,
    backgroundColor: '#eaf0df',
  },
  portionNutritionAmount: {
    fontSize: 19,
    fontWeight: '600',
    color: '#245d48',
  },
  empty: {
    paddingVertical: 35,
    alignItems: 'center',
    gap: 9,
  },
  mealSection: {
    marginTop: 14,
    borderWidth: 1,
    borderColor: '#e2e7dd',
    borderRadius: 12,
    overflow: 'hidden',
  },
  mealSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#f6f8f2',
  },
  mealSectionTitle: {
    flex: 1,
    minWidth: 0,
    lineHeight: 22,
  },
  mealSectionArrow: {
    fontSize: 18,
    color: '#607354',
  },
  mealInputSectionContent: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderColor: '#eef0e9',
  },
  mealInputSectionHeading: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  mealInputSectionHeader: {
    backgroundColor: '#e7eedc',
  },
  mealInputSectionHeaderText: {
    color: '#52654b',
  },
  mealRecord: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 8,
    borderTopWidth: 1,
    borderColor: '#eef0e9',
  },
  mealName: {
    flex: 1,
    minWidth: 0,
  },
  mealRecordActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  workoutCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginTop: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#e2e7dd',
    borderRadius: 12,
    backgroundColor: '#f1f5eb',
  },
  workoutOrder: {
    fontSize: 11,
    lineHeight: 19,
    fontWeight: '600',
    color: '#526174',
    marginBottom: 2,
  },
  overlay: {
    flex: 1,
    backgroundColor: '#17281e80',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  modal: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 25,
    width: '100%',
    maxWidth: 460,
    maxHeight: '90%',
  },
  calendarModal: {
    maxWidth: 390,
  },
  calendarMonthHeader: {
    marginTop: 12,
    marginBottom: 8,
  },
  calendarMonthLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2f4536',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarCell: {
    width: '14.2857%',
    padding: 2,
  },
  calendarWeekday: {
    textAlign: 'center',
    color: '#849078',
    paddingVertical: 8,
    fontSize: 12,
  },
  calendarDay: {
    minHeight: 42,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarToday: {
    borderWidth: 1,
    borderColor: '#245d48',
  },
  calendarSelectedDay: {
    backgroundColor: '#245d48',
  },
  calendarDayText: {
    fontSize: 14,
    color: '#2f4536',
  },
  calendarSelectedDayText: {
    color: '#fff',
    fontWeight: '600',
  },
  field: {
    marginTop: 20,
    gap: 8,
  },
  foodSuggestions: {
    borderWidth: 1,
    borderColor: '#dce3d5',
    borderRadius: 8,
    backgroundColor: '#fbfcf8',
    overflow: 'hidden',
  },
  foodSuggestionsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: '#e7eedc',
  },
  foodSuggestionOption: {
    minHeight: 56,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderColor: '#eef0e9',
  },
  foodSuggestionsEmpty: {
    padding: 12,
  },
  foodSearchActions: {
    padding: 12,
    gap: 8,
    alignItems: 'flex-start',
  },
  foodSearchLoading: {
    width: '100%',
    minHeight: 120,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  favoriteFoods: {
    marginTop: 16,
  },
  favoriteFoodsButton: {
    minHeight: 44,
    padding: 12,
    borderRadius: 8,
    backgroundColor: '#e7eedc',
  },
  favoriteFoodsList: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#dce3d5',
    borderRadius: 8,
    backgroundColor: '#fbfcf8',
    overflow: 'hidden',
  },
  favoriteFoodsEmpty: {
    padding: 14,
    gap: 4,
  },
  favoriteFoodsToolbar: {
    padding: 12,
    borderBottomWidth: 1,
    borderColor: '#eef0e9',
    alignItems: 'flex-start',
    gap: 4,
  },
  favoriteFoodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: '#eef0e9',
    paddingRight: 6,
  },
  favoriteFoodOption: {
    flex: 1,
    minHeight: 44,
    padding: 12,
  },
  favoriteFoodActions: {
    marginTop: 12,
    alignItems: 'flex-start',
    gap: 4,
  },
  label: {
    fontSize: 13,
    color: '#607354',
  },
  input: {
    borderWidth: 1,
    borderColor: '#dce3d5',
    backgroundColor: '#fbfcf8',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: '#263a30',
    minHeight: 46,
  },
  workoutSet: {
    marginTop: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#eef0e9',
    borderRadius: 8,
  },
  workoutOptions: {
    maxHeight: 240,
    borderWidth: 1,
    borderColor: '#dce3d5',
    borderRadius: 8,
    backgroundColor: '#fbfcf8',
  },
  workoutOption: {
    minHeight: 44,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  workoutSetFields: {
    flexDirection: 'row',
    gap: 10,
  },
  workoutSetField: {
    flex: 1,
  },
  error: {
    fontSize: 12,
    lineHeight: 20,
    color: '#a14332',
    marginTop: 14,
  },
});
